#import "template/hackathon.typ": *

#show: hackathon-doc.with(
  title: "REDACTED",
  subtitle: "Hide the person. Keep the document.",
  tagline: [
    Build an LLM-based system that finds and masks sensitive data in a
    document, preserving its meaning and formatting.
  ],
  location: "IST — Campus Taguspark, Porto Salvo, Lisbon",
  dates: "10–11 October 2026",
  cover: true,
  toc: false,
)

= The challenge

*Challenge one-liner:* build an LLM-based system that identifies and masks
sensitive or personal data in a document, keeping the document's meaning and
formatting intact.

#facts(
  ("Input", "1 shared document"),
  ("Output", "Masked text + prompt"),
  ("Pitch", "2 minutes max."),
)

== Introduction

Every team receives the same text document, filled with fictitious personal
data: `raw_data/document_to_anonymize.pdf`. Your system must replace the
sensitive data with asterisks and return the document with its original
formatting. The output is scored automatically when you open a pull request
against `main`.

Questions can be asked to the NOS mentors on site, or on the organisation's
Discord.

== The core of the challenge

+ *Detect.* Use prompt engineering to make the LLM recognise patterns and
  reason about the context around sensitive data, beyond its format.
+ *Mask.* Replace each anonymised word with a single `*`. A two-word name
  becomes two asterisks:

  ```text
  Ana Correia  ->  * *
  ```
+ *Preserve.* Keep the original formatting and the document's meaning. The only
  change in layout is that empty lines are removed. A correct output starts
  like this:

  ```text
  Relatório de Admissão - Centro Médico Lisboa
  Data: 15 de abril de 2025
  Referência: ADM-2025-04-15-089
  Informações do Paciente:
  ```
+ *Validate (optional).* Add a manual validation step to handle false
  positives and false negatives.

== Suggested technical components

- *Model:* Google Gemini, through the Gemini API (tutorial in
  `tutorials/gemini_tutorial.md`).
- *PDF to text:* PyMuPDF, as shown in `tutorials/pdf__to__txt.ipynb`.
- *Environment:* Python script or Jupyter / Colab notebook.
- *Version control:* Git and GitHub (tutorial in `tutorials/git_tutorial.md`).
- Open-source frameworks and packages are allowed, as long as they are
  referenced.

= Guidelines

== Before you start

#table(
  columns: (auto, 1fr),
  table.header[You need][How],
  [GitHub account], [#link("https://github.com/signup")[github.com/signup]],
  [Google account], [#link("https://accounts.google.com/signup")[accounts.google.com/signup]],
  [Google API key], [#link("https://aistudio.google.com/")[aistudio.google.com] → *Get API Key* → *Create API key* (under a new project)],
)

Save the generated API key in a safe place — you will need it later.

== Repository layout

#table(
  columns: (auto, 1fr),
  table.header[Path][What it holds],
  [`raw_data/`], [The document to anonymise.],
  [`submission/`], [`submission.txt`, `prompt.txt` and your code.],
  [`tutorials/`], [Problem statement, Gemini tutorial, Git tutorial, PDF-to-text notebook.],
  [`.github/workflows/`], [The automatic evaluation workflows.],
)

== Getting the repository

+ *Fork* the repository to your GitHub account. One fork per team: one member
  owns it and adds the others as collaborators.
+ *Clone* your fork and create a working branch, e.g. `team-<name>`.
+ Never work directly on `main`.
+ Work inside `submission/`.

= Submission

== What to deliver

Edit the two provided files and add your code:

#table(
  columns: (auto, 1fr),
  table.header[File][Content],
  [`submission/submission.txt`], [*Only* the output generated by your model or API, as your system returns it. This is what the judges evaluate.],
  [`submission/prompt.txt`], [The exact prompt used to generate that output.],
  [`submission/your-code`], [The notebook or script (`.py`, `.ipynb`) used to develop the solution. It is part of the evaluation.],
)

*Do not rename, move or delete the provided files.*

#callout(title: "Keep submission.txt clean", tone: "secondary")[
  Do not include the team name, project title, GitHub links, team members, any
  explanation or any extra formatting.
]

== How to submit

+ Run `git branch` and confirm you are on your own working branch.
+ Check the file status: `git status`.
+ Stage the files:
  `git add submission/submission.txt submission/prompt.txt submission/<your-code>`.
+ Commit: `git commit -m "Final submission -Team Name-"`.
+ Push: `git push origin <your-branch>`.
+ Open a *pull request* from your branch into `main` on GitHub.
+ Register your submission on the JunctionX platform, using the link of your
  pull request as the repository link.

Opening the pull request triggers the automatic evaluation workflows, so you
get a score as soon as you submit. The final submission must be in before the
end of the challenge.

= Evaluation and rules

== Evaluation criteria

#set table(inset: (x: 9pt, y: 4pt))
#table(
  columns: (1fr, auto),
  table.header[Criterion][Weight],
  [*Technical implementation*], [*40%*],
  [#h(10pt) Precision — detection hit rate], [10%],
  [#h(10pt) Prompt — prompt and response quality], [10%],
  [#h(10pt) Anonymisation quality — context preserved after removal], [5%],
  [#h(10pt) Explicability — clarity and technical rigour of the solution], [5%],
  [#h(10pt) Efficiency — optimised use of prompts and engineering techniques], [5%],
  [#h(10pt) GitHub — code quality: structure, branches, merges, commits], [5%],
  [*Collaboration* — shared commit history and integration between members], [*30%*],
  [*Documentation* — clarity, organisation and technical detail (README, usage, setup)], [*10%*],
  [*Pitch creativity* — originality, impact and communication], [*20%*],
)

== Automatic evaluation

Three GitHub Actions workflows run on your pull request:

- *Hackathon Evaluation* — compares `submission/submission.txt` with a hidden
  reference.
- *Prompt Evaluation* — scores `submission/prompt.txt`.
- *Lint Python Code* — runs `flake8` on the repository.

#callout(title: "A green check can hide a missing file", tone: "support")[
  If `submission.txt` or `prompt.txt` is missing, the matching workflow is
  skipped and still reports success, so a green check does not guarantee a
  score. Make sure both files are in your pull request.
]

== General rules

- Open-source frameworks and packages are allowed, as long as they are
  referenced.
- Every project must include clear documentation: README, usage and setup
  instructions.
- The commit history is analysed to evaluate good collaborative practices.
- The final pitch lasts at most 2 minutes per team.
- Failure to comply with the rules may mean immediate disqualification.

== Open-source intellectual property

- *Open-source licence:* the project's source code must be released under an
  open-source licence.
- *Public repository:* the code must be in a public repository (e.g. GitHub).
- *Repurpose:* the parties may reuse the work for other non-commercial
  purposes.

== Prizes

*1st:* Google certified course + summer internship at NOS. \
*2nd:* Google certified course. \
*3rd:* High-quality headphones.
